### ISSUE TITLE
XPoll for a Meeting should be nested in the same space

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-meeting#30]
https://jira.xwiki.org/browse/XAMEETINGS-135

**Comment by oanalavinia** [comment]
I discussed with Silvia and Cati and for motives of consistency the Poll should remain in the XPoll space. 
There could be problems when XPoll app is uninstalled because this will delete only polls from XPoll space, leaving those from Meeting space there. 
Also, even this functionality does not exists yet, maybe for future versions there could be made a reference to an existing poll and in this case the parent will be XPoll.

**Comment by mflorea** [comment]
> There could be problems when XPoll app is uninstalled because this will delete only polls from XPoll space, leaving those from Meeting space there.

The polls (wiki pages) are not removed when you uninstall the Poll application. Only the application **code** pages are removed.

**Comment by evalica** [comment]
- If we were to move Polls inside the Meetings space, than this behavior will be inconsistent with other (AWM) applications. The Meeting/XPoll apps would be an exception from the usual behavior. 
- In the future we might want to add more communications between applications, but this doesn't mean that all the entities should be moved. For example, you might want to reference a Calendar entry in a Meeting, or a Diagram inside a Meeting.
- The Poll and Meeting could be dependent, but there are use cases when they are independent and would need just a reference. 
- The Template Providers allow to suggest the creation of applications entries from other spaces, while forcing the location, so this can be implemented by using a Template Provider, and not from the Meeting's app code. 
- Since the creation of Polls is restricted by having the app installed, this means that when the app would be uninstalled, than the Polls won't be available anymore. 
- Our apps are pretty specialized, so having all the Polls in one place makes sense. From an implementation pov, we can have them nested, but that should be the exception, not the rule. 
- The only use case when a Poll is nested into a Meeting would help, would be when deleting a Meeting with all its 'dependencies'. But this means that the Poll is dedicated to the Meeting. This might or might not be the case. 
- Having the Polls into the XPoll space also helps in terms of discovery, since we would want to users to be encouraged to finds the polls and vote on them. Having it in the Meeting, isolated a bit the Poll. 

So, for this particular use case Poll/Meeting, I don't think is necessary to break the default behavior. 

We should check if the created poll was deleted meanwhile and mark the Meeting accordingly. Maybe preserving the broken link, so that the Admin could restore the Poll in case of need.

**Comment by evalica** [comment]
In case the XPoll app is uninstalled, even if the Poll page will be preserved under the Meeting, it will lack the display sheet, so it will look ugly.

**Comment by mflorea** [comment]
> Having the Polls into the XPoll space also helps in terms of discovery

The live table from the Poll application home page is most probably listing polls located **anywhere** (that's the default behavior when you create an application with AWM), so there's no discoverability issue I think.

**Comment by oanalavinia** [comment]
I tried and indeed the polls are from anywhere

**Comment by CostiChD** [comment]
How about adding a column in the livetable(from XPoll/WebHome) to show the connection between the poll and the Meeting App(maybe something like a "category") ? Now we see the polls listed, but we dont know exactly what is each poll about(unless the name gives enough information).

**Comment by lucaa** [comment]
@oanalavinia what's the conclusion of this issue, actually? it's closed but I don't understand if it was done or not or won't be done at all? I see no commit on it, so I guess it wasn't done?

**Comment by oanalavinia** [comment]
@lucaa I closed this issue because it didn't had enough votes for it to be done
