### ISSUE TITLE
Error in JS console which prevents Calendar to be loaded in some cases

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-meeting#84]
STEPS TO REPRODUCE

Environment: Windows 10 Pro 64bit, Chrome 87, using an instance of XWiki 12.10.2 on PostgreSQL 13, Tomcat 9.0.41, Meeting Pro 1.11.1

1. Login
2. Go to Meetings app
3. Click on 'Calendar' link
4. Hit CTRL + F5

EXPECTED RESULTS

Calendar page is loaded (refreshed).

ACTUAL RESULTS

The calendar is not loaded. In browser's JS console there is the following error:

![Calendar_view_error1](https://user-images.githubusercontent.com/32512703/105045755-f220b980-5a70-11eb-9df6-43fd7b1a08eb.png)

![Calendar_View_error2](https://user-images.githubusercontent.com/32512703/105045779-f6e56d80-5a70-11eb-8db7-d60af0d5c666.png)

In some cases, the calendar is not displayed just when navigating to Calendar page (without even hitting CTRL + F5).

**Comment by ignatescustefan** [comment]
This issue is related to this one from macro-fullcalendar: https://jira.xwiki.org/browse/FULLCAL-60 and needs to be fixed there. According to my investigations, this is reproducing only in the chrome browser.

**Comment by acotiuga** [comment]
This issue should be closed when the FullCalendar dependency version will be updated. It was fixed as part of https://jira.xwiki.org/browse/FULLCAL-60.

**Comment by mflorea** [comment]
@acotiuga I'm not sure the Won't Fix label is OK. In platform we close an issue that was fixed in a third party library **when we upgrade** the version of that third party library to include the fix. This way we know that the issue has been fixed in a specific version of the platform. In this case, this issue should be closed **when we upgrade** FullCalendar Macro, so that the release notes of the Meeting application lists the fixed bugs.
